[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_mint_nft = "2jQsP3H1gihzFUftqyhX32nm4s8knWXUxXWALESXNBHg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
